package com.example.ui.screens

import androidx.compose.animation.*
import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.testTag
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.example.ui.INKcoViewModel
import com.example.ui.theme.*

@Composable
fun CompanyScreen(viewModel: INKcoViewModel) {
    val companyName by viewModel.companyName.collectAsState()
    val companySubtitle by viewModel.companySubtitle.collectAsState()
    val companyImpressions by viewModel.companyImpressions.collectAsState()
    val companyRevenueGenerated by viewModel.companyRevenueGenerated.collectAsState()
    val companyRetainerRate by viewModel.companyRetainerRate.collectAsState()
    val companyManifesto by viewModel.companyManifesto.collectAsState()

    var showEditDialog by remember { mutableStateOf(false) }

    Box(modifier = Modifier.fillMaxSize()) {
        LazyColumn(
            modifier = Modifier
                .fillMaxSize()
                .testTag("company_view")
                .padding(horizontal = 16.dp),
            contentPadding = PaddingValues(top = 16.dp, bottom = 90.dp),
            verticalArrangement = Arrangement.spacedBy(16.dp)
        ) {
            // Hero Visual Section
            item {
                Box(
                    modifier = Modifier
                        .fillMaxWidth()
                        .height(200.dp)
                        .clip(RoundedCornerShape(20.dp))
                        .border(1.dp, ElectricBlue.copy(alpha = 0.3f), RoundedCornerShape(20.dp))
                        .background(
                            Brush.radialGradient(
                                colors = listOf(ElectricBlue.copy(alpha = 0.25f), DeepGrey),
                                radius = 600f
                            )
                        ),
                    contentAlignment = Alignment.Center
                ) {
                    Column(
                        horizontalAlignment = Alignment.CenterHorizontally,
                        modifier = Modifier.padding(16.dp)
                    ) {
                        TSILogo(size = 56.dp, showText = false)
                        Spacer(modifier = Modifier.height(10.dp))
                        Text(
                            text = companyName.uppercase(),
                            fontSize = 24.sp,
                            fontWeight = FontWeight.ExtraBold,
                            color = InkWhite,
                            letterSpacing = 2.sp,
                            textAlign = TextAlign.Center
                        )
                        Spacer(modifier = Modifier.height(6.dp))
                        Text(
                            text = companySubtitle.uppercase(),
                            fontSize = 10.sp,
                            color = ElectricBlue,
                            fontWeight = FontWeight.Bold,
                            fontFamily = FontFamily.Monospace,
                            letterSpacing = 1.sp,
                            textAlign = TextAlign.Center
                        )
                    }
                }
            }

            // Animated Statistics
            item {
                Row(
                    modifier = Modifier.fillMaxWidth(),
                    horizontalArrangement = Arrangement.spacedBy(8.dp)
                ) {
                    // Stat 1
                    GlassCard(modifier = Modifier.weight(1f)) {
                        Text(companyImpressions, fontSize = 20.sp, fontWeight = FontWeight.Bold, color = AccentGold)
                        Text("Organic Impressions", fontSize = 10.sp, color = TextSecondary)
                    }
                    // Stat 2
                    GlassCard(modifier = Modifier.weight(1f)) {
                        Text(companyRevenueGenerated, fontSize = 20.sp, fontWeight = FontWeight.Bold, color = ElectricBlue)
                        Text("Revenue Generated", fontSize = 10.sp, color = TextSecondary)
                    }
                    // Stat 3
                    GlassCard(modifier = Modifier.weight(1f)) {
                        Text(companyRetainerRate, fontSize = 20.sp, fontWeight = FontWeight.Bold, color = SuccessGreen)
                        Text("Client Retainer Rate", fontSize = 10.sp, color = TextSecondary)
                    }
                }
            }

            // Creative Pitch Intro
            item {
                GlassCard {
                    Text(
                        text = "THE BRAND MANIFESTO",
                        fontSize = 11.sp,
                        fontFamily = FontFamily.Monospace,
                        fontWeight = FontWeight.Bold,
                        color = ElectricBlue,
                        letterSpacing = 1.2.sp
                    )
                    Spacer(modifier = Modifier.height(8.dp))
                    Text(
                        text = companyManifesto,
                        fontSize = 14.sp,
                        color = TextPrimary,
                        lineHeight = 22.sp
                    )
                }
            }

            // Dynamic Leadership Profile Card (Inderneil Kanagali)
            item {
                GlassCard(
                    borderColor = AccentGold.copy(alpha = 0.3f),
                    backgroundColor = CardBg.copy(alpha = 0.8f),
                    glowColor = AccentGold.copy(alpha = 0.08f)
                ) {
                    Row(
                        verticalAlignment = Alignment.CenterVertically,
                        modifier = Modifier.fillMaxWidth()
                    ) {
                        Box(
                            modifier = Modifier
                                .size(72.dp)
                                .clip(CircleShape)
                                .background(AccentGold.copy(alpha = 0.15f))
                                .border(1.dp, AccentGold, CircleShape),
                            contentAlignment = Alignment.Center
                        ) {
                            Text("IK", color = AccentGold, fontSize = 22.sp, fontWeight = FontWeight.ExtraBold)
                        }

                        Spacer(modifier = Modifier.width(16.dp))

                        Column {
                            Text(
                                text = "INDERNEIL KANAGALI",
                                fontSize = 16.sp,
                                fontWeight = FontWeight.Bold,
                                color = InkWhite,
                                letterSpacing = 0.5.sp
                            )
                            Text(
                                text = "FOUNDER & BRAND STRATEGIST",
                                fontSize = 10.sp,
                                color = AccentGold,
                                fontFamily = FontFamily.Monospace,
                                fontWeight = FontWeight.Bold
                            )
                            Spacer(modifier = Modifier.height(4.dp))
                            Text(
                                text = "Synthesizing luxury aesthetics, performance analytics, and social science.",
                                fontSize = 11.sp,
                                color = TextSecondary
                            )
                        }
                    }
                }
            }

            // Services Catalog Accordion
            item {
                Text(
                    text = "DISCIPLINARY SERVICES",
                    fontSize = 11.sp,
                    fontFamily = FontFamily.Monospace,
                    fontWeight = FontWeight.Bold,
                    color = TextSecondary,
                    letterSpacing = 1.sp
                )
                Spacer(modifier = Modifier.height(6.dp))
                Column(verticalArrangement = Arrangement.spacedBy(10.dp)) {
                    val services = listOf(
                        Triple(Icons.Filled.Camera, "High-End Content Architecture", "Reels, Shorts, and cinematic POVs designed with fast viral retention algorithms."),
                        Triple(Icons.Filled.Speed, "Paid Media Optimization", "Performance ad sets engineered to deliver over 4x Return on Ad Spend (ROAS)."),
                        Triple(Icons.Filled.WorkspacePremium, "SaaS Brand Systems", "Visual and interactive identity configurations built to position startups for Series A funding.")
                    )
                    
                    services.forEach { (icon, title, desc) ->
                        Row(
                            modifier = Modifier
                                .fillMaxWidth()
                                .clip(RoundedCornerShape(12.dp))
                                .background(DeepGrey)
                                .border(1.dp, CardBorder, RoundedCornerShape(12.dp))
                                .padding(16.dp),
                            verticalAlignment = Alignment.CenterVertically
                        ) {
                            Box(
                                modifier = Modifier
                                    .size(36.dp)
                                    .clip(RoundedCornerShape(8.dp))
                                    .background(ElectricBlue.copy(alpha = 0.15f)),
                                contentAlignment = Alignment.Center
                            ) {
                                Icon(icon, title, tint = ElectricBlue, modifier = Modifier.size(18.dp))
                            }
                            Spacer(modifier = Modifier.width(16.dp))
                            Column(modifier = Modifier.weight(1f)) {
                                Text(title, color = InkWhite, fontSize = 13.sp, fontWeight = FontWeight.Bold)
                                Text(desc, color = TextSecondary, fontSize = 11.sp)
                            }
                        }
                    }
                }
            }

            // Interactive Timeline Nodes
            item {
                GlassCard {
                    Text(
                        text = "AGENCY GROWTH TIMELINE",
                        fontSize = 11.sp,
                        fontFamily = FontFamily.Monospace,
                        fontWeight = FontWeight.Bold,
                        color = ElectricBlue,
                        letterSpacing = 1.2.sp
                    )
                    Spacer(modifier = Modifier.height(14.dp))
                    
                    val eras = listOf(
                        "2024" to "The Social INK is incorporated, landing fintech retainers.",
                        "2025" to "Scale studios in major cities, handling luxury assets.",
                        "2026" to "Launched INKco modular automation operating deck."
                    )

                    eras.forEachIndexed { i, (year, label) ->
                        Row(
                            modifier = Modifier.fillMaxWidth().padding(bottom = 12.dp),
                            verticalAlignment = Alignment.Top
                        ) {
                            Column(horizontalAlignment = Alignment.CenterHorizontally) {
                                Box(
                                    modifier = Modifier
                                        .size(24.dp)
                                        .clip(CircleShape)
                                        .background(if (i == 2) ElectricBlue else DeepGrey)
                                        .border(1.dp, if (i == 2) ElectricBlue else CardBorder, CircleShape),
                                    contentAlignment = Alignment.Center
                                ) {
                                    Text(
                                        text = (i + 1).toString(),
                                        color = if (i == 2) InkWhite else TextSecondary,
                                        fontSize = 10.sp,
                                        fontWeight = FontWeight.Bold
                                    )
                                }
                                if (i < 2) {
                                    Box(
                                        modifier = Modifier
                                            .width(1.dp)
                                            .height(30.dp)
                                            .background(CardBorder)
                                    )
                                }
                            }
                            Spacer(modifier = Modifier.width(16.dp))
                            Column {
                                Text(year, color = if (i == 2) ElectricBlue else InkWhite, fontSize = 12.sp, fontWeight = FontWeight.Bold)
                                Text(label, color = TextSecondary, fontSize = 11.sp)
                            }
                        }
                    }
                }
            }

            // Customer Testimonials Carousel
            item {
                Text(
                    text = "CLIENT ACCOLADES",
                    fontSize = 11.sp,
                    fontFamily = FontFamily.Monospace,
                    fontWeight = FontWeight.Bold,
                    color = TextSecondary,
                    letterSpacing = 1.sp
                )
                Spacer(modifier = Modifier.height(6.dp))
                GlassCard {
                    Row(verticalAlignment = Alignment.CenterVertically) {
                        repeat(5) {
                            Icon(Icons.Filled.Star, "Star", tint = AccentGold, modifier = Modifier.size(16.dp))
                        }
                    }
                    Spacer(modifier = Modifier.height(8.dp))
                    Text(
                        text = "\"The Social INK completely scaled our marketing operations. Their content engines didn't just boost our followers—they drove a 48% surge in direct inbound demos in under 90 days.\"",
                        fontSize = 12.sp,
                        color = TextPrimary,
                        fontStyle = androidx.compose.ui.text.font.FontStyle.Italic
                    )
                    Spacer(modifier = Modifier.height(10.dp))
                    Text(
                        text = "— Chief Marketing Officer, Fintech Retainer",
                        fontSize = 11.sp,
                        color = ElectricBlue,
                        fontWeight = FontWeight.Bold
                    )
                }
            }
        }

        // Edit Company Floating Action Button
        FloatingActionButton(
            onClick = { showEditDialog = true },
            containerColor = ElectricBlue,
            contentColor = InkBlack,
            modifier = Modifier
                .align(Alignment.BottomEnd)
                .padding(bottom = 24.dp, end = 16.dp)
                .testTag("fab_edit_company")
        ) {
            Icon(Icons.Filled.Edit, contentDescription = "Edit agency deck details")
        }
    }

    if (showEditDialog) {
        var editName by remember { mutableStateOf(companyName) }
        var editSubtitle by remember { mutableStateOf(companySubtitle) }
        var editImpressions by remember { mutableStateOf(companyImpressions) }
        var editRevenue by remember { mutableStateOf(companyRevenueGenerated) }
        var editRetainer by remember { mutableStateOf(companyRetainerRate) }
        var editManifesto by remember { mutableStateOf(companyManifesto) }

        AlertDialog(
            onDismissRequest = { showEditDialog = false },
            title = { Text("Edit Agency Profile Specs", color = InkWhite) },
            text = {
                Column(
                    verticalArrangement = Arrangement.spacedBy(8.dp),
                    modifier = Modifier.verticalScroll(rememberScrollState())
                ) {
                    OutlinedTextField(
                        value = editName,
                        onValueChange = { editName = it },
                        label = { Text("Agency Name") },
                        colors = OutlinedTextFieldDefaults.colors(focusedTextColor = TextPrimary, unfocusedTextColor = TextPrimary),
                        modifier = Modifier.fillMaxWidth()
                    )
                    OutlinedTextField(
                        value = editSubtitle,
                        onValueChange = { editSubtitle = it },
                        label = { Text("Agency Tagline / Subtitle") },
                        colors = OutlinedTextFieldDefaults.colors(focusedTextColor = TextPrimary, unfocusedTextColor = TextPrimary),
                        modifier = Modifier.fillMaxWidth()
                    )
                    OutlinedTextField(
                        value = editImpressions,
                        onValueChange = { editImpressions = it },
                        label = { Text("Impressions Metric") },
                        colors = OutlinedTextFieldDefaults.colors(focusedTextColor = TextPrimary, unfocusedTextColor = TextPrimary),
                        modifier = Modifier.fillMaxWidth()
                    )
                    OutlinedTextField(
                        value = editRevenue,
                        onValueChange = { editRevenue = it },
                        label = { Text("Revenue Metric") },
                        colors = OutlinedTextFieldDefaults.colors(focusedTextColor = TextPrimary, unfocusedTextColor = TextPrimary),
                        modifier = Modifier.fillMaxWidth()
                    )
                    OutlinedTextField(
                        value = editRetainer,
                        onValueChange = { editRetainer = it },
                        label = { Text("Retainer Rate %") },
                        colors = OutlinedTextFieldDefaults.colors(focusedTextColor = TextPrimary, unfocusedTextColor = TextPrimary),
                        modifier = Modifier.fillMaxWidth()
                    )
                    OutlinedTextField(
                        value = editManifesto,
                        onValueChange = { editManifesto = it },
                        label = { Text("Brand Manifesto") },
                        colors = OutlinedTextFieldDefaults.colors(focusedTextColor = TextPrimary, unfocusedTextColor = TextPrimary),
                        modifier = Modifier.fillMaxWidth().height(120.dp)
                    )
                }
            },
            confirmButton = {
                TextButton(
                    onClick = {
                        viewModel.updateCompanySpecs(
                            name = editName,
                            subtitle = editSubtitle,
                            impressions = editImpressions,
                            revenue = editRevenue,
                            retainer = editRetainer,
                            manifesto = editManifesto
                        )
                        showEditDialog = false
                    }
                ) {
                    Text("Save Specs", color = ElectricBlue)
                }
            },
            dismissButton = {
                TextButton(onClick = { showEditDialog = false }) {
                    Text("Cancel", color = TextSecondary)
                }
            },
            containerColor = DeepGrey
        )
    }
}
